### ISSUE TITLE
Danish language not working

### ISSUE THREAD

**Issue by nsb** [resmio/reputation-widget#14]
When the browser language and facility language is danish the widget shows english text.

<img width="847" alt="skaermbillede 2016-11-30 kl 12 27 20" src="https://cloud.githubusercontent.com/assets/16436/20750716/887466b4-b6f8-11e6-92a5-ec64a6ae3ba8.png">

**Comment by menor** [comment]
In which language is your OS?

**Comment by menor** [comment]
Can we close this one @nsb ?
Is your OS in english?
