### ISSUE TITLE
make default size of badge smaller

### ISSUE THREAD

**Issue by mmarder** [resmio/reputation-widget#16]
Its too big for most restaurant websites.

**Comment by menor** [comment]
Default is 100% of the parent, with a min of 200px and a max of 500px so it will grow to fill the parent element, if they don't know CSS we have to options:
1- Make it take an (optional) parameter for the width
```
<div
    class="resmio-reputation-widget"
    data-resmio-reputation-id="the-fish"
    data-resmio-reputation-language="es"
    data-resmio-reputation-color="yellow"
    data-resmio-reputation-width="200px" 
  ></div>
```

2- make them add this to the pasteable code:
```
<div style='width:200px;' >
  <div
    class="resmio-reputation-widget"
    data-resmio-reputation-id="the-fish"
    data-resmio-reputation-language="es"
    data-resmio-reputation-color="yellow"
   ></div>
</div>
```

Let me know which one do you prefer (I prefer 2)

**Comment by mmarder** [comment]
maybe just add: data-resmio-reputation-max-width="200px" ?

**Comment by menor** [comment]
Ok, do we want to make that optional or for everyone?

**Comment by menor** [comment]
data-resmio-reputation-max-width="200px"
also move min-width to 150px
